builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
docker_manifests:
  - name_template: "jensschulze/php-fpm_exporter:latest"
    image_templates:
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "jensschulze/php-fpm_exporter:{{ .Major }}"
    image_templates:
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "ghcr.io/jensschulze/php-fpm_exporter:latest"
    image_templates:
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"
  - name_template: "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}"
    image_templates:
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/jensschulze/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"

changelog:
  filters:
    exclude:
      - "^docs:"

archives:
  - id: default
    format: binary
  - id: targz
    format: tar.gz
